spring:
   application:
      name: naming-server
   cloud:
      config:
         import-check:
            enabled: false
server:
   port: 8761
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false